# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
